all : anjaligrep clean
main : main.o file.o ll.o
	cc main.o file.o ll.o -o anjaligrep
main.o : main.c ll.h header.h
	cc -c main.c -wall
file.o : file.c header.h ll.h ll.o
	cc -c file.c -Wall
ll.o : ll.c ll.h
	cc -c ll.c -Wall
clean :
	rm *.o